apiVersion: v1
kind: Namespace
metadata:
  name: bcvvbbfvbvb-prod
  labels:
    environment-id: env_461fad43-39eb-4f37-898d-70ef5c52948d
    project-id: project_e9971512-9918-4c0a-999c-24cf449e5268
    project-name: bcvvbbfvbvb
    environment-name: prod
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
